#!/usr/bin/env bash
# get domain name and dns record type

get_record_info() {
    domain=$1
    subdomain=$2
    record_type=$(dig +short $subdomain.$domain | awk '{print $5}')
    destination=$(dig +short $subdomain.$domain | awk '{print $NF}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    get_record_info $domain www
    get_record_info $domain lb-01
    get_record_info $domain web-01
    get_record_info $domain web-02
else
    get_record_info $domain $subdomain
fi