#!/bin/env bash
# Install nginx web server
apt-get update -y

apt-get install -y nginx


echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

service nginx restart

