#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install -y haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo " listen load_balancer
	bind*:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 249173-web-01 52.91.148.46:80 check
	server 249173-web-02 52.201.187.130:80 check
" >> /etc/haproxy/haproxy.cfg

haproxy -f /etc/haproxy/haproxy.cfg -c

