#!/usr/bin/env bash
# print files in the dir line by line

for file in *;
do
    if [ -f "$file" ] && [[ "$file" != .* ]];
	then
        	filename=$(echo "$file" | cut -d '-' -f 2-)
        	echo "$filename"
    fi
done
